os: osx
osx_image: xcode14.3
language: swift
script: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
